######################## default configuration ####################
baseURL = "https://www.natureworks.org.uk"
languageCode = "en-gb"
title = "Nature Works"
theme = "icelab-hugo"
summaryLength = "10"


############################## Output ###############################
[outputs]
home = ["HTML", "RSS"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################## Output ###############################
# JS Plugins
[[params.plugins.js]]
URL = "plugins/plugins.js"


############################## navigation ###########################
[[menu.main]]
name = "Portfolio"
URL = "portfolio"
weight = 2

[[menu.main]]
name = "Design"
URL = "design"
weight = 3

[[menu.main]]
name = "Courses"
URL = "courses"
weight = 4

[[menu.main]]
name = "Livestream"
URL = "livestream"
weight = 5


#################### default parameters ##############################
[params]
logo = "https://res.cloudinary.com/growdigital/image/upload/v1630698563/natureworks/logo.png"
home = "Home"
# Meta data
description = "Wildlife & Forest Garden Design"
author = "Jake Rayson"
cloudinary = "https://res.cloudinary.com/growdigital/image/upload/"
images = [ "https://res.cloudinary.com/growdigital/image/upload/w_1240,q_60/v1544219005/valeriana-41717565655-169.jpg" ]
imageAlt = [ "Hoverfly on small pinkish flowers" ]

# footer content
footer_content = "Email: hello@natureworks.org.uk Phone: 07802 535 321"

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

###  Social site
[[params.social]]
name = "YouTube"
icon = "fa-youtube" # fontawesome icon pack v4.7
link = "https://www.youtube.com/c/natureworksgarden"

[[params.social]]
name = "Instagram"
icon = "fa-instagram" # fontawesome icon pack v4.7
link = "https://instagram.com/NatureWorksGarden"

[[params.social]]
name = "Facebook"
icon = "fa-facebook" # fontawesome icon pack v4.7
link = "https://facebook.com/NatureWorksGarden"

[[params.social]]
name = "Twitter"
icon = "fa-twitter" # fontawesome icon pack v4.7
link = "https://twitter.com/NatureWorksGdn"

### Display articles at root
[permalinks]
articles = "/:title"
